; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@DialogSizeScatter@@2UQMetaObject@@B ; DialogSizeScatter::staticMetaObject
PUBLIC	?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DialogSizeScatter::qt_static_metacall
EXTRN	?staticMetaObject@AbstractDialog@@2UQMetaObject@@B:BYTE ; AbstractDialog::staticMetaObject
CONST	SEGMENT
$SG263258 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
$SG268427 DB	'%s', 00H
	ORG $+9
$SG263259 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG263260 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG263597 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG263598 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG263599 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG263936 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG263937 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG263938 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@DialogSizeScatter@@2UQMetaObject@@B DQ FLAT:?staticMetaObject@AbstractDialog@@2UQMetaObject@@B ; DialogSizeScatter::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_DialogSizeScatter@@3Uqt_meta_stringdata_DialogSizeScatter_t@@B
	DQ	FLAT:?qt_meta_data_DialogSizeScatter@@3QBIB
	DQ	FLAT:?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
?qt_meta_stringdata_DialogSizeScatter@@3Uqt_meta_stringdata_DialogSizeScatter_t@@B DD 0ffffffffH ; qt_meta_stringdata_DialogSizeScatter
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000090H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	000000000000008aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000079H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000062H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000055H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	0000000000000043H
	DB	044H
	DB	069H
	DB	061H
	DB	06cH
	DB	06fH
	DB	067H
	DB	053H
	DB	069H
	DB	07aH
	DB	065H
	DB	053H
	DB	063H
	DB	061H
	DB	074H
	DB	074H
	DB	065H
	DB	072H
	DB	00H
	DB	075H
	DB	070H
	DB	064H
	DB	061H
	DB	074H
	DB	065H
	DB	00H
	DB	00H
	DB	075H
	DB	070H
	DB	064H
	DB	061H
	DB	074H
	DB	065H
	DB	043H
	DB	065H
	DB	06cH
	DB	06cH
	DB	00H
	DB	061H
	DB	070H
	DB	070H
	DB	06cH
	DB	079H
	DB	00H
	DB	063H
	DB	061H
	DB	06eH
	DB	063H
	DB	065H
	DB	06cH
	DB	00H
	ORG $+6
	ORG $+8
?qt_meta_data_DialogSizeScatter@@3QBIB DD 08H		; qt_meta_data_DialogSizeScatter
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	022H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	023H
	DD	02H
	DD	08H
	DD	04H
	DD	00H
	DD	024H
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	025H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG264766 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG264767 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG264768 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG265171 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG265172 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG265173 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG265564 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG265565 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG265566 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG265957 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG265958 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG265959 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG266350 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG266351 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG266352 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG266743 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG266744 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG266745 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG267136 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG267137 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG267138 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG267529 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG267530 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG267531 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG259668 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG259669 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG259670 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG267922 DB	'D:\Qt\5.12.5\msvc2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG267923 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG267924 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG268426 DB	'invalid argument', 00H
	ORG $+15
$SG268428 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG268429 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG268430 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG268431 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+10
$SG268626 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@DialogSizeScatter@@UEBAPEBUQMetaObject@@XZ ; DialogSizeScatter::metaObject
PUBLIC	?qt_metacast@DialogSizeScatter@@UEAAPEAXPEBD@Z	; DialogSizeScatter::qt_metacast
PUBLIC	?qt_metacall@DialogSizeScatter@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; DialogSizeScatter::qt_metacall
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	?qt_metacast@AbstractDialog@@UEAAPEAXPEBD@Z:PROC ; AbstractDialog::qt_metacast
EXTRN	?qt_metacall@AbstractDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC ; AbstractDialog::qt_metacall
EXTRN	?update@DialogSizeScatter@@AEAAXXZ:PROC		; DialogSizeScatter::update
EXTRN	?updateCell@DialogSizeScatter@@AEAAXXZ:PROC	; DialogSizeScatter::updateCell
EXTRN	?apply@DialogSizeScatter@@AEAAXXZ:PROC		; DialogSizeScatter::apply
EXTRN	?cancel@DialogSizeScatter@@AEAAXXZ:PROC		; DialogSizeScatter::cancel
pdata	SEGMENT
$pdata$?metaObject@DialogSizeScatter@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@DialogSizeScatter@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@DialogSizeScatter@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+74
	DD	imagerel $unwind$?qt_metacast@DialogSizeScatter@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@DialogSizeScatter@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$?qt_metacall@DialogSizeScatter@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN11
	DD	imagerel $LN11+129
	DD	imagerel $unwind$?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@DialogSizeScatter@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@DialogSizeScatter@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@DialogSizeScatter@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; DialogSizeScatter::qt_static_metacall
; File D:\SiliconVisualiser\SiliconVisualiser\x64\Debug\moc\moc_DialogSizeScatter.cpp
; Line 76
$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 77
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 78
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 80
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN8@qt_static_
	jmp	SHORT $LN9@qt_static_
$LN5@qt_static_:
; Line 81
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?update@DialogSizeScatter@@AEAAXXZ	; DialogSizeScatter::update
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 82
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?updateCell@DialogSizeScatter@@AEAAXXZ	; DialogSizeScatter::updateCell
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 83
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?apply@DialogSizeScatter@@AEAAXXZ	; DialogSizeScatter::apply
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?cancel@DialogSizeScatter@@AEAAXXZ	; DialogSizeScatter::cancel
$LN9@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 89
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; DialogSizeScatter::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@DialogSizeScatter@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; DialogSizeScatter::qt_metacall
; File D:\SiliconVisualiser\SiliconVisualiser\x64\Debug\moc\moc_DialogSizeScatter.cpp
; Line 115
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 116
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacall@AbstractDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; AbstractDialog::qt_metacall
	mov	DWORD PTR _id$[rsp], eax
; Line 117
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 119
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 120
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN5@qt_metacal
; Line 121
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@DialogSizeScatter@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; DialogSizeScatter::qt_static_metacall
$LN5@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 123
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 124
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN7@qt_metacal
; Line 125
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 126
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 129
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@DialogSizeScatter@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; DialogSizeScatter::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@DialogSizeScatter@@UEAAPEAXPEBD@Z PROC	; DialogSizeScatter::qt_metacast
; File D:\SiliconVisualiser\SiliconVisualiser\x64\Debug\moc\moc_DialogSizeScatter.cpp
; Line 107
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 108
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 109
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_DialogSizeScatter@@3Uqt_meta_stringdata_DialogSizeScatter_t@@B+144
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 110
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 111
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacast@AbstractDialog@@UEAAPEAXPEBD@Z ; AbstractDialog::qt_metacast
$LN1@qt_metacas:
; Line 112
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@DialogSizeScatter@@UEAAPEAXPEBD@Z ENDP	; DialogSizeScatter::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@DialogSizeScatter@@UEBAPEBUQMetaObject@@XZ PROC ; DialogSizeScatter::metaObject
; File D:\SiliconVisualiser\SiliconVisualiser\x64\Debug\moc\moc_DialogSizeScatter.cpp
; Line 102
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 103
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@DialogSizeScatter@@2UQMetaObject@@B ; DialogSizeScatter::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 104
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@DialogSizeScatter@@UEBAPEBUQMetaObject@@XZ ENDP ; DialogSizeScatter::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File D:\Qt\5.12.5\msvc2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File D:\SiliconVisualiser\SiliconVisualiser\x64\Debug\moc\moc_DialogSizeScatter.cpp
; Line 132
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File D:\SiliconVisualiser\SiliconVisualiser\x64\Debug\moc\moc_DialogSizeScatter.cpp
; Line 132
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
